#!/usr/bin/env bash
# Usage:
#   bash scripts/submit_sweep.sh  <yaml>  <group_name>  [max_concurrent]
#
# * <yaml>         — path to the sweep YAML generated by generate_configs.py
# * <group_name>   — becomes the SLURM job name (and is passed to the array wrapper)
# * [max_concurrent] optional; if supplied, adds %N to the array for concurrency cap

## Example usage
# # No concurrency cap (all jobs eligible at once)
# bash scripts/submit_sweep.sh bllarse_sweeps/my_sweep.yaml my_sweep

# # Limit to 15 running simultaneously
# bash scripts/submit_sweep.sh bllarse_sweeps/my_sweep.yaml my_sweep 15

set -euo pipefail

yaml=$1
group=$2
max_concurrent=${3-}          # empty string if not provided

rows=$(yq '. | length' "$yaml")   # number of configs
end=$((rows-1))

echo "Submitting $rows jobs (0-$end) for group '$group'"

# build the --array flag
if [[ -z "$max_concurrent" ]]; then
    array_flag="--array=0-${end}"
else
    array_flag="--array=0-${end}%${max_concurrent}"
fi

sbatch $array_flag \
       scripts/run_slurm_finetuning_array.sh \
       "$yaml" "$group"
